apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /kubernetes-demo

