version: '3.4'

services:

  trend.mongo:
    container_name: trend.mongo
    volumes:
      - ./data/mongo/trend:/data/db
    command: "mongod --bind_ip_all --replSet myreplica --keyFile /opt/keyfile/mongo-keyfile"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trendpassword
      
  redis:
    container_name: redis
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"

  identity.database:
    container_name: identity_database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa55w0rd!
    ports:
      - 1433:1433
    volumes:
      - ./data/identity/data:/var/opt/mssql/data
      - ./data/identity/log:/var/opt/mssql/log
      - ./data/identity/secrets:/var/opt/mssql/secrets
    platform: linux/amd64

  sql.server.tools:
    container_name: msql_tools
    depends_on:
      - identity.database
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S identity.database -U sa -P pa55w0rd! -Q "create database Keycloak"; do sleep 5; done'

  keycloak:
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KC_DB=mssql
      - KC_TRANSACTION_XA_ENABLED=false
      - KC_DB_URL=jdbc:sqlserver://identity.database;databaseName=Keycloak;encrypt=false;trustServerCertificate=false;
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=pa55w0rd!
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    depends_on:
      - identity.database
      - sql.server.tools

  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq

  jaeger-all-in-one:
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
        
  dynamodb-mailservice-db:
    container_name: dynamodb-mailservice-db
    hostname: localhost
    volumes:
      - dynamodb-mailservice-db-store:/home/dynamodblocal
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"

  postgre-db:
    container_name: postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=florijan
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgre/data:/var/lib/postgresql/data
     
  azurite:
    container_name: azurite
    ports:
      - 10000:10000
    command: "azurite --loose --skipApiVersionCheck --blobHost 0.0.0.0 --blobPort 10000 --location /workspace --debug /workspace/debug.log" 
    volumes:
      - ./data/azurite/:/workspace

    