version: '3.4'

services:

  trend.mongo:
    image: culix77/mongo-replica

  redis:
    image: redis:7.2.1
 
  keycloak: 
    image: quay.io/keycloak/keycloak:23.0

  rabbitmq:
    image: masstransit/rabbitmq

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.51
    
  otel-collector:
    image: otel/opentelemetry-collector:latest
    
  dynamodb-mailservice-db:
    image: amazon/dynamodb-local:1.21.0
    
  postgre-db:
    image: timescale/timescaledb:latest-pg14

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
  
  crypto.api:
    image: crypto.api
    build:
      context: .
      dockerfile: src/Services/Crypto/Crypto.API/Dockerfile

volumes:
  mongodbstore:
  redisstore:
  identitysqlvolume:
  rabbitmqstore:
  eventstore-volume-data:
  eventstore-volume-logs:
  notification-hub-redis-store:
  dynamodb-mailservice-db-store:
  pgadmin-volume:


