version: '3.4'

services:

  trend.mongo:
    container_name: trend_mongo_db
    volumes:
      - mongodbstore:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trendpassword
  
  trend.redis:
    container_name: trend_redis
    volumes:
      - redisstore:/data
    ports:
      - "6379:6379"


