version: '3.4'

services:

  trend.mongo:
    image: culix77/mongo-replica

  redis:
    image: redis:7.2.1
 
  identity.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
  sql.server.tools:
    image: mcr.microsoft.com/mssql-tools

  keycloak: 
    image: culix77/keycloak:latest

  rabbitmq:
    image: masstransit/rabbitmq

  jager:
    image: jaegertracing/all-in-one:1.43
    
  dynamodb-mailservice-db:
    image: amazon/dynamodb-local:1.21.0
    
  postgre-db:
    image: postgres:13

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite

volumes:
  mongodbstore:
  redisstore:
  identitysqlvolume:
  rabbitmqstore:
  eventstore-volume-data:
  eventstore-volume-logs:
  notification-hub-redis-store:
  dynamodb-mailservice-db-store:
  pgadmin-volume:
