version: '3.4'

services:

  trend.mongo:
    container_name: trend_mongo_db
    volumes:
      - mongodbstore:/data/db
      - mongodbstore:/data/configdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trendpassword
  
  trend.redis:
    container_name: trend_redis
    volumes:
      - redisstore:/data
    ports:
      - "6379:6379"

  identity.database:
    container_name: identity_database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa55w0rd!
    ports:
      - 1433:1433
    volumes:
      - identitysqlvolume:/var/opt/mssql

  sql.server.tools:
    container_name: msql_tools
    depends_on:
      - identity.database
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S identity.database -U sa -P pa55w0rd! -Q "create database Keycloak"; do sleep 5; done'

  keycloak:
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD=pa55w0rd!
      - DB_ADDR=identity.database
      - DB_DATABASE=Keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    depends_on:
      - identity.database
      - sql.server.tools

  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqstore:/var/lib/rabbitmq

  notification.hub.redis:
    container_name: notification.hub.redis
    ports:
      - "6380:6379"
    volumes:
      - notification-hub-redis-store:/data

  jager:
    container_name: jager
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
        
  dynamodb-mailservice-db:
    container_name: dynamodb-mailservice-db
    hostname: localhost
    volumes:
      - dynamodb-mailservice-db-store:/home/dynamodblocal
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"

  tracker-postgre-db:
    container_name: tracker-postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=florijan
    ports:
      - "5432:5432"
    volumes:
      - tracker-postgre-volume:/var/lib/postgresql/data

  stock-postgre-db:
    container_name: stock-postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=florijan
    ports:
      - "5433:5432"
    volumes:
      - stock-postgre-volume:/var/lib/postgresql/data
        
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    
    