version: '3.4'

services:
  trend.mongo:
    container_name: trend_mongo_db
    volumes:
      - mongodbstore:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trendpassword

  mongo.express:
    container_name: mongo_express


