version: '3.4'

services:

  trend.mongo:
    container_name: trend_mongo_db
    volumes:
      - mongodbstore:/data/db
      - mongodbstore:/data/configdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trendpassword
  
  trend.redis:
    container_name: trend_redis
    volumes:
      - redisstore:/data
    ports:
      - "6379:6379"

  identity.database:
    container_name: identity_database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa55w0rd!
    ports:
      - 1433:1433
    volumes:
      - identitysqlvolume:/var/opt/mssql

  sql.server.tools:
    container_name: msql_tools
    depends_on:
      - identity.database
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S identity.database -U sa -P pa55w0rd! -Q "create database Keycloak"; do sleep 5; done'

  keycloak:
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD=pa55w0rd!
      - DB_ADDR=identity.database
      - DB_DATABASE=Keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    depends_on:
      - identity.database
      - sql.server.tools

  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqstore:/var/lib/rabbitmq

  eventstore.db:
    container_name: eventstore.db
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore-volume-data:/var/lib/eventstore
      - eventstore-volume-logs:/var/log/eventstore

  notification.hub.redis:
    container_name: notification.hub.redis
    ports:
      - "6380:6379"
    volumes:
      - notification-hub-redis-store:/data

  jager:
    container_name: jager
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"