version: '3.4'

services:

  trend.mongo:
    hostname: mongo
    container_name: trend.mongo
    volumes:
      - ./data/mongo/trend:/data/db
    command: "mongod --bind_ip_all --replSet myreplica --keyFile /opt/keyfile/mongo-keyfile"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trendpassword
      
  redis:
    hostname: redis
    container_name: redis
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"

  keycloak:
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgre-db/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak!
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    depends_on: 
      - postgre-db

  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
      
  jaeger-all-in-one:
    ports:
      - "16686:16686"
      - "4318:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
        
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./data/otelcollector/config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./data/otelcollector/output:/etc/output:rw 
    ports:
      - "4317:4317" 
    depends_on:
      - jaeger-all-in-one
        
  dynamodb-mailservice-db:
    container_name: dynamodb-mailservice-db
    hostname: localhost
    volumes:
      - dynamodb-mailservice-db-store:/home/dynamodblocal
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"

  postgre-db:
    container_name: postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=florijan
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgre/data:/var/lib/postgresql/data
     
  azurite:
    container_name: azurite
    ports:
      - 10000:10000
    command: "azurite --loose --skipApiVersionCheck --blobHost 0.0.0.0 --blobPort 10000 --location /workspace --debug /workspace/debug.log" 
    volumes:
      - ./data/azurite/:/workspace

    