receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  logging:
    verbosity: detailed
    tls:
      insecure: true
    default_labels_enabled:
      exporter: false
      job: true
      instance: true
      level: true
  otlp/jaeger:
    endpoint: http://jaeger-all-in-one:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/jaeger]
  extensions: []
