#file: noinspection YAMLSchemaValidation
version: 2.1

orbs:
  1password: onepassword/secrets@1.0.0

jobs:
  build_and_test:
    machine:
      image: ubuntu-2204:current
    steps:
    - run:
        name: Install .NET SDK
        command: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0 jq
    - checkout
    - run:
        name: Start docker compose
        command: |
          cd ./ops/local
          docker compose up -d
    - run:
        name: Restore packages
        command: dotnet restore ./PortfolioTracker.sln
    - run:
        name: Build microservices
        command: dotnet build ./PortfolioTracker.sln --no-restore
    - run:
        name: Run integration tests
        command: |
          dotnet test ./PortfolioTracker.sln --no-build --no-restore --nologo --logger "trx;LogFileName=TestResults.trx" --results-directory:"test-results"
    - run:
        name: Convert test results
        command: |
          dotnet tool install -g trx2junit || true
          export PATH="$PATH:/home/circleci/.dotnet/tools"
          trx2junit test-results/TestResults.trx
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results

  build_docker_images:
    docker:
    - image: cimg/base:stable
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - 1password/install-cli:
        version: 2.30.0
    - run:
        name: "Login to docker hub"
        shell: op run -- /bin/bash
        environment:
          DOCKER_PASSWORD: op://CircleCI/Docker/password
        command: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
    - run:
        name: "Build docker images"
        working_directory: ops/images
        command: chmod +x build-images.sh && ./build-images.sh
    - run:
        name: "Prepare image tags"
        working_directory: ops/images
        command: |
          docker tag crypto.api "$DOCKER_USER/crypto.api:$CIRCLE_SHA1"
    - run:
        name: "Push images"
        working_directory: ops/images
        command: |
          docker push "$DOCKER_USER/crypto.api:$CIRCLE_SHA1"
    - run:
        name: "Logout from docker hub"
        command: |
          docker logout

workflows:
  build_and_deploy:
    jobs:
    - build_and_test
    - build_docker_images:
        filters:
          branches:
            only:
            - release
