#file: noinspection YAMLSchemaValidation
version: 2.1

orbs:
  1password: onepassword/secrets@1.0.0

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
    - run:
        name: Install .NET SDK
        command: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0 jq
    - checkout
    - run:
        name: Start docker compose
        command: |
          cd ./ops/local
          docker compose up -d
    - run:
        name: Restore packages
        command: dotnet restore PortfolioTracker.sln
    - run:
        name: Build microservices
        command: dotnet build PortfolioTracker.sln --no-restore
    - run:
        name: Run integration tests
        command: dotnet test PortfolioTracker.sln --no-build --no-restore --nologo -p:CollectTestOutput=true -p:TestOutputDir=/tmp/TestResults
    - store_artifacts:
        path: /tmp/TestResults
        destination: TestResults
    - store_test_results:
        path: /tmp/TestResults/

workflows:
  build_test:
    jobs:
    - build
