/**
 * Trend.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpValidationProblemDetails } from './http-validation-problem-details';
import { ProblemDetails } from './problem-details';


/**
 * @type GetDefaultAllValue400Response
 * @export
 */
export type GetDefaultAllValue400Response = HttpValidationProblemDetails | ProblemDetails;

