/**
 * Trend.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchWordResDto { 
    id?: string;
    isActive?: boolean;
    created?: Date;
    searchWord?: string;
    searchEngineName?: string;
    searchEngineId?: number;
    contextTypeName?: string;
    contextTypeId?: number;
    imageUrl?: string;
}

