/**
 * Trend.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SyncStatusWordResDto } from './sync-status-word-res-dto';


export interface SyncStatusResDto { 
    id?: string | null;
    started?: Date;
    finished?: Date;
    totalRequests?: number;
    succeddedRequests?: number;
    searchWords?: Array<SyncStatusWordResDto> | null;
}

