version: '3.4'
name: portfolio

services:

  redis:
    image: redis:7.4.1-alpine
    container_name: portfolio.redis
    restart: unless-stopped
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  postgre:
    image: timescale/timescaledb:latest-pg14
    container_name: portfolio.postgre
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=florijan
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgre/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  rabbitmq:
    image: masstransit/rabbitmq:3.13.1
    container_name: portfolio.rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: portfolio.keycloak
    ports:
      - 8080:8080
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgre/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak!
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: [ "start-dev" ]
    depends_on:
      postgre:
        condition: service_healthy
