connection_string: 'amqp://rabbitmquser:rabbitmqpassword@localhost:5672'

default_delivery_mode: 2
default_content_type: 'application/vnd.masstransit+json'

img_uploaded_con:
  root_exchange:
    name: 'Events.Common.User:UserImageUploaded'
  intermediate_exchange:
    name: 'user-image-uploaded'
  queue:
    name: 'user-image-uploaded'
  dotnet_namespace: 'Events.Common.User:UserImageUploaded'
  masstransit_type: 'urn:message:Events.Common.User:UserImageUploaded'

img_verified_pub:
  root_exchange_name: 'Events.Common.User:UserImageVerified'
  dotnet_namespace: 'Events.Common.User:UserImageVerified'
  masstransit_type: 'urn:message:Events.Common.User:UserImageVerified'
