apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgre-statefulset
  labels:
    app: postgre
spec:
  serviceName: postgre-service
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: timescale/timescaledb:latest-pg14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgre-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgre-data
        persistentVolumeClaim:
          claimName: postgre-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgre-service
spec:
  selector:
    app: postgre
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
