- name: Get Keycloak admin access token
  uri:
    url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body:
      "grant_type=password&\
        client_id=admin-cli&\
        username=admin&\
        password=admin"
    body_format: form-urlencoded
    return_content: yes
  register: auth_response
  failed_when: auth_response.status != 200

- name: Extract access token
  set_fact:
    access_token: "{{ auth_response.json.access_token }}"

- name: Check if realm exists
  uri:
    url: "{{ keycloak_url }}/admin/realms/{{ realm_name }}"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token }}"
    status_code: [200, 404]
  register: realm_check_response

- name: Create realm if it doesn't exist
  uri:
    url: "{{ keycloak_url }}/admin/realms"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token }}"
      Content-Type: "application/json"
    body:
      realm: "{{ realm_name }}"
      enabled: true
    body_format: json
    status_code: 201
  when: realm_check_response.status == 404