- name: Create keycloak clients
  loop: "{{ clients }}"
  community.general.keycloak_client:
    realm: "{{ realm_name }}"
    auth_realm: "master"
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_client_id: "admin-cli"
    auth_username: "admin"
    auth_password: "{{ realm_admin_password }}"
    state: present
    client_id: "{{ item.name }}"
    enabled: true
    public_client: true
    standard_flow_enabled: "{{ item.standard_flow_enabled }}"
    implicit_flow_enabled: "{{ item.implicit_flow_enabled }}"
    redirect_uris:
      - "{{ item.redirect_uri }}"
    web_origins:
      - "{{ item.web_origin }}"
    
- name: Get public_key property from keycloack URL
  uri:
    url: "{{ keycloak_url }}/realms/{{ realm_name }}"
    method: GET
    return_content: yes
  register: response

- name: Extract public_key from JSON response
  debug:
    msg: "The public_key is: {{ response.json.public_key }}"

- name: Prepare appsettings for development environment
  loop: "{{ clients }}"
  ansible.builtin.template:
    src: "{{ item.template_name }}"
    dest: "{{ item.app_settings_path }}"
  vars:
    public_keycloak_key: "{{ response.json.public_key }}"