// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Api.GeneratedCode
{
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "0.8.5.0")]
    public partial interface ICryptoApi
    {
        [Headers("Accept: text/plain, application/json, text/json")]
        [Post("/api/v1/Crypto/AddNew")]
        Task AddNew([Body] AddNewCommand body);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Post("/api/v1/Crypto/AddNewWithDelay")]
        Task<IApiResponse<System.Guid?>> AddNewWithDelay([Body] AddNewWithDelayCommand body);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Post("/api/v1/Crypto/UndoAddNewDelay")]
        Task UndoAddNewDelay([Body] UndoNewWithDelayCommand body);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Put("/api/v1/Crypto/UpdateInfo")]
        Task UpdateInfo([Body] UpdateInfoCommand body);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Put("/api/v1/Crypto/UpdatePrice")]
        Task UpdatePrice([Body] UpdatePriceCommand body);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Put("/api/v1/Crypto/UpdateAllPrices")]
        Task UpdateAllPrices();

        [Headers("Accept: text/plain, application/json, text/json")]
        [Get("/api/v1/Crypto/FetchPage")]
        Task<IApiResponse<ICollection<FetchPageResponseDto>>> FetchPage([Query, AliasAs("Page")] int? page, [Query, AliasAs("Take")] int? take);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Get("/api/v1/Crypto/Single/{symbol}")]
        Task<IApiResponse<FetchSingleResponseDto>> Single(string symbol);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Get("/api/v1/Crypto/GetPriceHistory/{cryptoId}")]
        Task<IApiResponse<ICollection<PriceHistoryDto>>> GetPriceHistory(System.Guid cryptoId);

        [Headers("Accept: text/plain, application/json, text/json")]
        [Get("/api/v1/Crypto/GetMostPopular")]
        Task<IApiResponse<ICollection<GetMostPopularResponse>>> GetMostPopular([Query, AliasAs("Take")] int? take);
    }

    [System.CodeDom.Compiler.GeneratedCode("Refitter", "0.8.5.0")]
    public partial interface IInfoApi
    {
        [Get("/api/v1/Info/AssemblyVersion")]
        Task AssemblyVersion();
    }


}


//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"

namespace Api.GeneratedCode
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class AddNewCommand
    {

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

        [JsonPropertyName("correlationId")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public System.Guid? CorrelationId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class AddNewWithDelayCommand
    {

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class FetchPageResponseDto
    {

        [JsonPropertyName("id")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public System.Guid Id { get; set; }

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

        [JsonPropertyName("name")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Name { get; set; }

        [JsonPropertyName("website")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Website { get; set; }

        [JsonPropertyName("sourceCode")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string SourceCode { get; set; }

        [JsonPropertyName("price")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public double Price { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class FetchSingleResponseDto
    {

        [JsonPropertyName("id")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public System.Guid Id { get; set; }

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

        [JsonPropertyName("name")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Name { get; set; }

        [JsonPropertyName("price")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public double Price { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class GetMostPopularResponse
    {

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

        [JsonPropertyName("count")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public int Count { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class PriceHistoryDto
    {

        [JsonPropertyName("cryptoId")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public System.Guid CryptoId { get; set; }

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

        [JsonPropertyName("name")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Name { get; set; }

        [JsonPropertyName("website")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Website { get; set; }

        [JsonPropertyName("sourceCode")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string SourceCode { get; set; }

        [JsonPropertyName("timeBucket")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public System.DateTimeOffset TimeBucket { get; set; }

        [JsonPropertyName("avgPrice")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public double AvgPrice { get; set; }

        [JsonPropertyName("maxPrice")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public double MaxPrice { get; set; }

        [JsonPropertyName("minPrice")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public double MinPrice { get; set; }

        [JsonPropertyName("lastPrice")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public double LastPrice { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class ProblemDetails
    {

        [JsonPropertyName("type")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Type { get; set; }

        [JsonPropertyName("title")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Title { get; set; }

        [JsonPropertyName("status")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public int? Status { get; set; }

        [JsonPropertyName("detail")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Detail { get; set; }

        [JsonPropertyName("instance")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Instance { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class UndoNewWithDelayCommand
    {

        [JsonPropertyName("temporaryId")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public System.Guid TemporaryId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class UpdateInfoCommand
    {

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class UpdatePriceCommand
    {

        [JsonPropertyName("symbol")]

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]   
        public string Symbol { get; set; }

    }


}