apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit-statefulset
  labels:
    app: rabbit
spec:
  serviceName: rabbit-service
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: masstransit/rabbitmq
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-secret
              key: RABBITMQ_DEFAULT_PASS
        volumeMounts:
        - name: rabbit-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbit-data
        persistentVolumeClaim:
          claimName: rabbit-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  selector:
    app: rabbit
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
